// // // Student data from the provided JSON
// export const studentData = [
//   { Name: "Chaing polin", Gender: "Male", "Advanced Subject": "Foundation Afternoon" },
//   { Name: "PhalPhea Pheakdey", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation" },
//   { Name: "Kay Kang", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation" },
//   { Name: "Va Eric", Gender: "Male", "Advanced Subject": "Full Stack-1st Generation" },
//   { Name: "Kong Sisovandara", Gender: "Male", "Advanced Subject": "Full Stack-1st Generation" },
//   { Name: "Mao Piseth", Gender: "Male", "Advanced Subject": "Association-1st Generation" },
//   { Name: "Vuth sarandy", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation" },
//   { Name: "Nouth Chanraksa", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation" },
//   { Name: "ព្រីង សុវណ្ណវត្តី ", Gender: "Female", "Advanced Subject": "Association-1st Generation"},
//   { Name: "Art Vandeth ", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation" },
//   { Name: "Chey Somatra", Gender: "Male", "Advanced Subject": "Full Stack-1st Generation" },
//   { Name: "Long Poseth", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation" },
//   { Name: "Phou Kukseng", Gender: "Male", "Advanced Subject": "Full Stack-1st Generation" },
//   { Name: "Ing Muyleang", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-1st-Generation" },
//   { Name: "Pos Panha", Gender: "Female", "Advanced Subject": "ISTAD-ITE-Scholar-1st-Generation" },
//   { Name: "Sin Meanborey", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-1st-Generation" },
//   { Name: "Leang Helen", Gender: "Female", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation" },
//   { Name: "Proeung Chiso", Gender: "Male", "Advanced Subject":"ISTAD-ITE-Scholar-2nd-Generation"},
//   { Name: "Yeng SokRoza", Gender: "Female", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation"},
//   { Name: "On Soben" , Gender: "Female", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation"},
//   { Name: "Sorn Sophamrinet", Gender: "Female", "Advanced Subject": "Full Stack-1st Generation"},
//   { Name: "Luy Kanika", Gender: "Female", "Advanced Subject": "Foundation-2nd Generation"},
//   { Name: "Heng Sothib", Gender: "Female", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation"},
//   { Name: "Hom Pheakakvotey", Gender: "Female", "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation"},
//   { Name: "Leang Naikim", Gender: "Female" , "Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation"},
//   { Name: "seang sengleaph", Gender: "Male", "Advanced Subject": "ISTAD-ITE-Scholar-1st-Generation"},
//   { Name: "Chan samangrathana", Gender: "Female","Advanced Subject": "ISTAD-ITE-Scholar-2nd-Generation"},
//   { Name: "Oun Markara", Gender: "Male", "Advanced Subject": "Foundation-3rd Generation"},
// ]



// Student data from the provided JSON
export const studentData = 
[
  { "Full_Name": "Va Eric" },
  { "Full_Name": "Tith Cholna" },
  { "Full_Name": "CHENG DEVITH" },
  { "Full_Name": "Mao Piseth" },
  { "Full_Name": "Chey Somatra" },
  { "Full_Name": "THOEUN VANLY" },
  { "Full_Name": "CHAN SAMNANG" },
  { "Full_Name": "Thai Ratanak" },
  { "Full_Name": "Seu Narong" },
  { "Full_Name": "KiryRatanak" },
  { "Full_Name": "Ey Channim" },
  { "Full_Name": "Kong Sisovandara" },
  { "Full_Name": "DINA PISETHI" },
  { "Full_Name": "Vat Laihoun" },
  { "Full_Name": "BEN THONA" },
  { "Full_Name": "មួង ម៉ីនាង" },
  { "Full_Name": "Meng Kimleap" },
  { "Full_Name": "មួង ម៉ីនាង" },
  { "Full_Name": "Rin Bunvarn" },
  { "Full_Name": "HEANH CHANRAKSMEY" },
  { "Full_Name": "Mom Lisa" },
  { "Full_Name": "Seoung reaksa" },
  { "Full_Name": "Theoun Seyha" },
  { "Full_Name": "San Sengthanu" },
  { "Full_Name": "Dy Chhean" },
  { "Full_Name": "Phoem Oudom" },
  { "Full_Name": "Toch Ratana" },
  { "Full_Name": "LUN KOEMTRY" },
  { "Full_Name": "Tourn Vuthy" },
  { "Full_Name": "Sorn Sophamarinet" },
  { "Full_Name": "Mom Rotha" },
  { "Full_Name": "Kim Chanthorn" },
  { "Full_Name": "Chit Chimy" },
  { "Full_Name": "SamBath SamBer" },
  { "Full_Name": "Taing Sengkim" },
  { "Full_Name": "Kao Sengheang" },
  { "Full_Name": "Kay Kang" },
  { "Full_Name": "Soeurn VIsal" },
  { "Full_Name": "Ben Loemheng" },
  { "Full_Name": "Mom Raksmey" },
  { "Full_Name": "Pech Rattanakmony" },
  { "Full_Name": "Hor Ratha" },
  { "Full_Name": "Lor Vengroth" },
  { "Full_Name": "Chamreun Molikatevy" },
  { "Full_Name": "CHHAO CHHANNON" },
  { "Full_Name": "Soeng Yanut" },
  { "Full_Name": "Lor Vengroth" },
  { "Full_Name": "Puthy Lyhong" },
  { "Full_Name": "Nourv Sithikun" },
  { "Full_Name": "Ren Makara" },
  { "Full_Name": "Chhorn SeavLeng" },
  { "Full_Name": "ង៉ូវ គឹមស៊ូហេង" },
  { "Full_Name": "Heng Longchhor" },
  { "Full_Name": "Pho Hongleap" },
  { "Full_Name": "Sam Sokunsreypich" },
  { "Full_Name": "Sim Menghor" },
  { "Full_Name": "Khann Kanhchana" },
  { "Full_Name": "Sam Sreynich" },
  { "Full_Name": "Ches Sovanreach" },
  { "Full_Name": "ភឿន សូលីតា" },
  { "Full_Name": "Khann Kanhchana" },
  { "Full_Name": "រឿម តារា" },
  { "Full_Name": "Dim pathea" },
  { "Full_Name": "លីម ឡុងហ៊្វូ" },
  { "Full_Name": "VEL SOTHOUN" },
  { "Full_Name": "Thoeurn Chanthat" },
  { "Full_Name": "Ny Rosa" },
  { "Full_Name": "Srun Oudomsambath" },
  { "Full_Name": "Liep Sokkeang" },
  { "Full_Name": "Srey Chanchhay" },
  { "Full_Name": "Dorn Dana" },
  { "Full_Name": "Chhay Davin" },
  { "Full_Name": "លេង សុវណ្ណរិទ្ធី" },
  { "Full_Name": "Mon Narea" },
  { "Full_Name": "Houng Mingyeak" },
  { "Full_Name": "Khorn Sokkhim" },
  { "Full_Name": "But SeavThong" },
  { "Full_Name": "Maiy Leangngim" },
  { "Full_Name": "Hong Vanndeth" },
  { "Full_Name": "Leang Lyjing" },
  { "Full_Name": "ភឿន សូលីតា" },
  { "Full_Name": "Bun Raksa" },
  { "Full_Name": "Rayya Yuma" },
  { "Full_Name": "Khorn Sokkhim" },
  { "Full_Name": "Tollah hamadabidin" },
  { "Full_Name": "SAN TOL" },
  { "Full_Name": "LENG SAROTH" },
  { "Full_Name": "Mon Narea" },
  { "Full_Name": "Ches Sovanreach" },
  { "Full_Name": "NGOV KIMSOUHENG" },
  { "Full_Name": "Lot Los" },
  { "Full_Name": "Ky Reaksa" },
  { "Full_Name": "ស៊ីម មេងហ៊" },
  { "Full_Name": "Mong Sokkhouch" },
  { "Full_Name": "Thai Ratanak" },
  { "Full_Name": "Tong Bora" },
  { "Full_Name": "Srey Chanchhay" },
  { "Full_Name": "Chhay Kongkea" },
  { "Full_Name": "Kim Chanthorn" },
  { "Full_Name": "កើត វ៉ាត់" },
  { "Full_Name": "Theoun Seyha" },
  { "Full_Name": "Lonh Raksmey" },
  { "Full_Name": "LONG Bin" },
  { "Full_Name": "Sorn Sophiram" },
  { "Full_Name": "Saren Ratanak" },
  { "Full_Name": "Taing Sengkim" },
  { "Full_Name": "Vong Kormva" },
  { "Full_Name": "សាក់ វិសាល" },
  { "Full_Name": "Soeurt Bomnorng" },
  { "Full_Name": "Vuth Vatana" },
  { "Full_Name": "Chhorn SeavLeng" },
  { "Full_Name": "Sou Phallin" },
  { "Full_Name": "Korm Taingan" },
  { "Full_Name": "vorn soroth" },
  { "Full_Name": "Ho Hav" },
  { "Full_Name": "Thai Vathanak" },
  { "Full_Name": "Chhat Sovanney" },
  { "Full_Name": "លឹម សុវត្ថា" },
  { "Full_Name": "Lim Ansoleaphea" },
  { "Full_Name": "Teng Meng Houy" },
  { "Full_Name": "Koy Sophea" },
  { "Full_Name": "Lim Sovatha" },
  { "Full_Name": "KiryRatanak" },
  { "Full_Name": "Thoeun Vanly" },
  { "Full_Name": "សារុន លីសា" },
  { "Full_Name": "Nov raksa" },
  { "Full_Name": "Ratana Oudom" },
  { "Full_Name": "Saroeun Sothearith" },
  { "Full_Name": "Kung Sovannda" },
  { "Full_Name": "Hean Sitha" },
  { "Full_Name": "Dim Pathea" },
  { "Full_Name": "ឆេង បញ្ញារតន៍" },
  { "Full_Name": "Seng SilKhema" },
  { "Full_Name": "Mom Lisa" },
  { "Full_Name": "Ren Makara" },
  { "Full_Name": "Lut Lina" },
  { "Full_Name": "Yuhan Lorn" },
  { "Full_Name": "Kry Sobothty" },
  { "Full_Name": "Chaing polin" },
  { "Full_Name": "Houng Mingyeak" }
]




