// Student data from the provided JSON
export const studentData = [
  { Name: "Yeng Sokroza", Gender: "Female", "Advanced Subject": "Data Analytics" },
  { Name: "Phal Seakngim", Gender: "Female", "Advanced Subject": "Spring" },
  { Name: "Leang Helen", Gender: "Female", "Advanced Subject": "Cybersecurity" },
  { Name: "Hom pheakakvotey", Gender: "Female", "Advanced Subject": "Cybersecurity" },
  { Name: "Art Vandeth", Gender: "Male", "Advanced Subject": "Spring" },
  { Name: "Pol Sokkhann", Gender: "Male", "Advanced Subject": "Spring" },
  { Name: "Chan samangrathana", Gender: "Female", "Advanced Subject": "Spring" },
  { Name: "Phy Lymann", Gender: "Male", "Advanced Subject": "Data Analytics" },
  { Name: "Sanh Panha ", Gender: "Male", "Advanced Subject": "Blockchain" },
  { Name: "Leang Naikim ", Gender: "Female", "Advanced Subject": "Flutter" },
  { Name: "Long Piseth", Gender: "Male", "Advanced Subject": "Spring" },
  { Name: "Sol Vathanak", Gender: "Male", "Advanced Subject": "DevOps" },
  { Name: "Srorng Sokcheat", Gender: "Female", "Advanced Subject": "Blockchain" },
  { Name: "Phiv Lyhou", Gender: "Male", "Advanced Subject": "Cybersecurity" },
  { Name: "Chhem Chhunhy", Gender: "Female", "Advanced Subject": "Data Analytics" },
  { Name: "Hout Sovannarith", Gender: "Male", "Advanced Subject": "Data Analytics" },
  { Name: "Ruos Sovanra", Gender: "Male", "Advanced Subject": "DevOps" },
  { Name: "Thoeng Mengseu", Gender: "Male", "Advanced Subject": "Spring" },
  { Name: "Channtha Seamey", Gender: "Female", "Advanced Subject": "Data Analytics" },
  { Name: "Heng Sothib", Gender: "Female", "Advanced Subject": "Flutter" },
  { Name: "Nouth chanraksa", Gender: "Male", "Advanced Subject": "Blockchain" },
  { Name: "Noun sovanthorn", Gender: "Female", "Advanced Subject": "Flutter" },
  { Name: "Yith Sopheaktra", Gender: "Male", "Advanced Subject": "Spring" },
  { Name: "PhalPhea Pheakdey", Gender: "Male", "Advanced Subject": "Cybersecurity" },
  { Name: "Phal Sophanmai", Gender: "Female", "Advanced Subject": "Spring" },
  { Name: "on soben", Gender: "Male", "Advanced Subject": "DevOps" },
  { Name: "Mom Makara", Gender: "Male", "Advanced Subject": "DevOps" },
  { Name: "Pov Sokny", Gender: "Male", "Advanced Subject": "DevOps" },
  { Name: "Eung Lyzhia", Gender: "Female", "Advanced Subject": "Spring" },
  { Name: "pov soknem", Gender: "Male", "Advanced Subject": "Spring" },
  { Name: "Vuth sarandy", Gender: "Male", "Advanced Subject": "Spring" },
  { Name: "Chhoeurn kimla ", Gender: "Male", "Advanced Subject": "Data Analytics" },
  { Name: "Nhoem Tevy ", Gender: "Female", "Advanced Subject": "Flutter" },
  { Name: "Kay Kang", Gender: "Male", "Advanced Subject": "Blockchain" },
  { Name: "Heng Layhak", Gender: "Male", "Advanced Subject": "DevOps" },
]
